### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [AidanZeber/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by AidanZeber** [comment]
Ken - went ahead and added the <meta name="viewport" content="width=device-width, initial-scale=1"> to the <head> in the application.html.erb file. Mobile is now much easier to view, as the page now loads on mobile to populate the entire screen without zooming out on the page.

**Comment by kenmazaika** [comment]
Thumbs up.  Great work, I looked at your code and it looks perfect.  :+1:
